### ISSUE TITLE
`exec` pickup name if in the right folder

### ISSUE THREAD

**Issue by lawrencegripper** [stuartleeks/devcontainer-cli#31]
I'm thinking it would be nice to run `devcontainer exec` and have it pull the devcontainer name from the `devcontainer.json` if you're in a folder with a `.devcontainer`. 

With the work on #30 this would mean just running `devcontainer exec` would drop you into a terminal for the container. 

What do you think - sound like a reasonable plan?

**Comment by stuartleeks** [comment]
I like the idea!

That might make the meaning of the positional arguments ambiguous since you can do `devcontainer exec dc-name my-app arg1 arg2 arg3` (at least I think it supports that!)

So with:
`devcontainer exec myapp some-arg`
vs
`devcontainer exec dc-name myapp`

I'm not clear how you'd do that reliably.

Maybe a breaking change is needed:

`devcontainer exec --container=dc-name my-app arg1 ...`

where `--container` is optional if you're in a folder for a dev container?

**Comment by lawrencegripper** [comment]
That's a very good point. Yeah a breaking change to use named args feels like a good way out of this `--container`. 

With both now being optional I can't see another way to disambiguate them.

**Comment by stuartleeks** [comment]
I've been mulling this over a bit more and I think this is a change that makes sense. However, since it's a breaking change I figure it warrants a bit of thought to try to avoid another breaking change later :-)

The current `devcontainer exec` experience is:

```bash
# Run `bash args...` in `dc-name` dev container
devcontainer exec dc-name bash args...

# Prompt to select dev container and run bash
devcontainer exec ? bash
```

If we change this to use switches, one question I had was whether the `command` and `args` should also be switches. I think I'm leaning towards keeping them as positional arguments as it feels more usable - any thoughts?

```bash
#
# Convert to switches to set dev container
# Allows more options by avoiding issues with parameter ambiguity: anything after the switches is the command and args
#  --prompt to prompt instead of the magic `?` => better discoverability
#  --path to specify dev container by folder rather than name
#  --work-dir to specify the folder within the container to use as the working directory
#

# Run `bash args...` in `dc-name` dev container
devcontainer exec --name dc-name bash args...

# Run `bash args...` in `dc-name` dev container with the working directory set to `/some/path`
devcontainer exec --name dc-name --work-dir /some/path bash args...

# Prompt to select dev container and run bash
devcontainer exec --prompt bash

# Run `bash` in the dev container for the project at `~/ source/my-proj`
devcontainer exec --path ~/source/my-proj bash

# If container not specified, assume `--path .`?
devcontainer exec bash

# If command/args not set, assume `bash`?
devcontainer exec --name dc-name

# Combining these to launch bash in the dev container for the project in the current directory:
devcontainer exec


# Other notes
#  - only allow one of --name/--path/--prompt
```

**Comment by lawrencegripper** [comment]
This looks good to me, maps in my head to the syntax of `docker run` some params then two positional args

**Comment by stuartleeks** [comment]
Cool - thanks @lawrencegripper  :-)
